version: '3'

services:
  database:
    build:
          context: .
          dockerfile: Dockerfile-service1
    container_name: GEC_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: devuser
      MYSQL_USER_PASSWORD: devpass
  web:
    build:
          context: .
          dockerfile: Dockerfile-service2
    container_name: GEC
    depends_on:
      - database
    ports:
      - "8081:80"
    
  