FROM php:7.0-apache
COPY . /var/www/html
RUN apt-get update
RUN apt-get install -y nano
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN apt-get install -y net-tools
EXPOSE 80

