version: '3'

services:
  db:
    build:
          context: .
          dockerfile: Dockerfile-service1
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build:
          context: .
          dockerfile: Dockerfile-service2
    container_name: GEC
    depends_on:
      - db
    ports:
      - "8100:80"
    
  